"""Warning and milestone messages, in every locale the stories are told in.

These were English string literals in the detectors, so a run narrated in
Farsi or French showed English in its warning strip and timeline — the one
part of the dashboard that says something is wrong. The VS Code extension's
engine uses the same catalogue (generated by scripts/gen_ts_engine_tables.py).

Placeholders are ``{name}`` and are filled by plain substitution, as the
narrative templates are, so both engines fill them identically.
"""

from __future__ import annotations

MESSAGES: dict[str, dict[str, str]] = {
    "en": {
        "warn_nan": "Something went wrong — the loss became undefined. "
        "The teacher may need to lower the learning rate.",
        "warn_spike": "The loss has spiked unexpectedly. "
        "The model may have stepped too far in one direction.",
        "warn_climb": "The loss is climbing away from where it started. "
        "The teacher may need to lower the learning rate.",
        "warn_overfit": "The model may be memorising the study material "
        "instead of understanding it.",
        "warn_plateau": "Learning has slowed. The model has stopped finding new patterns.",
        "warn_lr_drop": "Learning rate decreased from {old} to {new}.",
        "ms_best": "New best: {value}",
        "ms_crossed": "Crossed {pct}%: {value}",
        "ms_biggest_jump": "Biggest single-epoch improvement: {value}",
        "ms_complete": "Training completed.",
        # Kinds only the extension's engine emits.
        "ms_first_metric": "First {metric} recorded: {value}",
        "ms_grade_up": "Grade improved to {grade}",
        "ms_grade_down": "Grade dropped to {grade}",
        "ms_phase": "Entered the {phase} phase",
        "phase_awakening": "awakening",
        "phase_learning": "learning",
        "phase_understanding": "understanding",
        "phase_mastering": "mastering",
        "phase_polishing": "polishing",
    },
    "fa": {
        "warn_nan": "مشکلی پیش آمد — مقدار loss تعریف‌نشده شد. "
        "شاید معلم باید نرخ یادگیری را پایین بیاورد.",
        "warn_spike": "loss ناگهان جهش کرد. شاید مدل در یک جهت بیش از حد پیش رفته باشد.",
        "warn_climb": "loss از نقطه‌ی شروعش دور می‌شود و بالا می‌رود. "
        "شاید معلم باید نرخ یادگیری را پایین بیاورد.",
        "warn_overfit": "شاید مدل به‌جای فهمیدن مطالب، آن‌ها را حفظ می‌کند.",
        "warn_plateau": "یادگیری کند شده است. مدل دیگر الگوی تازه‌ای پیدا نمی‌کند.",
        "warn_lr_drop": "نرخ یادگیری از {old} به {new} کاهش یافت.",
        "ms_best": "بهترین مقدار تازه: {value}",
        "ms_crossed": "از {pct}% گذشت: {value}",
        "ms_biggest_jump": "بزرگ‌ترین بهبود در یک دوره: {value}",
        "ms_complete": "آموزش به پایان رسید.",
        "ms_first_metric": "اولین مقدار {metric}: {value}",
        "ms_grade_up": "نمره به {grade} بهبود یافت",
        "ms_grade_down": "نمره به {grade} افت کرد",
        "ms_phase": "ورود به مرحله‌ی {phase}",
        "phase_awakening": "بیداری",
        "phase_learning": "یادگیری",
        "phase_understanding": "درک",
        "phase_mastering": "تسلط",
        "phase_polishing": "پالایش",
    },
    "fr": {
        "warn_nan": "Quelque chose s'est mal passé — la loss est devenue indéfinie. "
        "Le professeur devrait peut-être baisser le taux d'apprentissage.",
        "warn_spike": "La loss a bondi brusquement. "
        "Le modèle a peut-être fait un pas trop grand dans une direction.",
        "warn_climb": "La loss remonte et s'éloigne de son point de départ. "
        "Le professeur devrait peut-être baisser le taux d'apprentissage.",
        "warn_overfit": "Le modèle mémorise peut-être la matière au lieu de la comprendre.",
        "warn_plateau": "L'apprentissage ralentit. Le modèle ne trouve plus de nouveaux motifs.",
        "warn_lr_drop": "Le taux d'apprentissage est passé de {old} à {new}.",
        "ms_best": "Nouveau meilleur résultat : {value}",
        "ms_crossed": "Seuil de {pct} % franchi : {value}",
        "ms_biggest_jump": "Plus forte amélioration en une époque : {value}",
        "ms_complete": "Entraînement terminé.",
        "ms_first_metric": "Première mesure de {metric} : {value}",
        "ms_grade_up": "Note améliorée : {grade}",
        "ms_grade_down": "Note en baisse : {grade}",
        "ms_phase": "Nouvelle phase : {phase}",
        "phase_awakening": "éveil",
        "phase_learning": "apprentissage",
        "phase_understanding": "compréhension",
        "phase_mastering": "maîtrise",
        "phase_polishing": "perfectionnement",
    },
}


def phase_name(phase: str, locale: str = "en") -> str:
    """A training phase's name, capitalised, in *locale*.

    The exporters printed `phase.title()` — English in a French or Farsi
    report — beside a translated everything else.
    """
    key = f"phase_{phase}"
    if key not in MESSAGES["en"]:
        return phase.title()
    name = message(key, locale)
    return name[:1].upper() + name[1:]


def message(key: str, locale: str = "en", **fields: str) -> str:
    """The message *key* in *locale* (English when there is none), filled in."""
    table = MESSAGES.get(locale, MESSAGES["en"])
    text = table.get(key, MESSAGES["en"][key])
    for name, value in fields.items():
        text = text.replace("{" + name + "}", value)
    return text
