// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine
// (story_engine/grade.py, phases.py, warnings.py, __init__.py).
// Do not edit: change the Python and regenerate.

export type TaskType = "classification" | "detection" | "segmentation" | "regression" | "biometric" | "gaze" | "nlp" | "generative" | "custom";
export type Grade = "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D" | "F" | "I";
export type Phase = "awakening" | "learning" | "understanding" | "mastering" | "polishing";
export type Threshold = [Grade, number];

/** Letter grades best first, without I (incomplete). */
export const GRADE_ORDER: readonly Grade[] = ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "F"];

/** Bands per task, best first; a task without its own uses classification's. */
export const DEFAULT_THRESHOLDS: Readonly<Record<TaskType, readonly Threshold[]>> = {
  classification: [["A+", 0.95], ["A", 0.9], ["A-", 0.87], ["B+", 0.82], ["B", 0.75], ["B-", 0.7], ["C+", 0.65], ["C", 0.6], ["C-", 0.55], ["D", 0.5], ["F", 0.0]],
  detection: [["A+", 0.75], ["A", 0.65], ["A-", 0.58], ["B+", 0.5], ["B", 0.42], ["B-", 0.35], ["C+", 0.28], ["C", 0.2], ["C-", 0.15], ["D", 0.08], ["F", 0.0]],
  segmentation: [["A+", 0.85], ["A", 0.78], ["A-", 0.72], ["B+", 0.66], ["B", 0.6], ["B-", 0.54], ["C+", 0.47], ["C", 0.4], ["C-", 0.32], ["D", 0.2]],
  regression: [["A+", 0.01], ["A", 0.05], ["A-", 0.1], ["B+", 0.2], ["B", 0.35], ["B-", 0.5], ["C+", 0.7], ["C", 1.0], ["C-", 1.5], ["D", 2.5], ["F", Infinity]],
  biometric: [["A+", 0.01], ["A", 0.03], ["A-", 0.05], ["B+", 0.08], ["B", 0.1], ["B-", 0.15], ["C+", 0.2], ["C", 0.25], ["C-", 0.3], ["D", 0.4], ["F", Infinity]],
  gaze: [["A+", 0.5], ["A", 1.0], ["A-", 1.5], ["B+", 2.5], ["B", 4.0], ["B-", 6.0], ["C+", 9.0], ["C", 12.0], ["C-", 16.0], ["D", 22.0], ["F", Infinity]],
  nlp: [["A+", 10.0], ["A", 20.0], ["A-", 30.0], ["B+", 50.0], ["B", 80.0], ["B-", 120.0], ["C+", 180.0], ["C", 250.0], ["C-", 350.0], ["D", 500.0], ["F", Infinity]],
  generative: [["A+", 0.95], ["A", 0.9], ["A-", 0.87], ["B+", 0.82], ["B", 0.75], ["B-", 0.7], ["C+", 0.65], ["C", 0.6], ["C-", 0.55], ["D", 0.5], ["F", 0.0]],
  custom: [["A+", 0.95], ["A", 0.9], ["A-", 0.87], ["B+", 0.82], ["B", 0.75], ["B-", 0.7], ["C+", 0.65], ["C", 0.6], ["C-", 0.55], ["D", 0.5], ["F", 0.0]],
};

export const LOWER_BETTER_TASKS: ReadonlySet<TaskType> = new Set(["biometric", "gaze", "nlp", "regression"]);

/** Bands that belong to a metric rather than a task (R2 carries its own scale). */
export const METRIC_THRESHOLDS: Readonly<Record<string, readonly Threshold[]>> = {
  "R2": [["A+", 0.95], ["A", 0.9], ["A-", 0.85], ["B+", 0.8], ["B", 0.7], ["B-", 0.6], ["C+", 0.5], ["C", 0.4], ["C-", 0.3], ["D", 0.1], ["F", -Infinity]],
  "val_R2": [["A+", 0.95], ["A", 0.9], ["A-", 0.85], ["B+", 0.8], ["B", 0.7], ["B-", 0.6], ["C+", 0.5], ["C", 0.4], ["C-", 0.3], ["D", 0.1], ["F", -Infinity]],
};

export const DIRECTION_BY_KEY: Readonly<Record<string, boolean>> = {"balanced_accuracy": false, "bpc": true, "brier": true, "cer": true, "error_rate": true, "explained_variance": false, "far": true, "fid": true, "huber": true, "inception_score": false, "is_score": false, "kappa": false, "kid": true, "l1": true, "l2": true, "log_loss": true, "lpips": true, "mape": true, "mcc": false, "medae": true, "meteor": false, "mrr": false, "ndcg": false, "nll": true, "pearson": false, "pixel_accuracy": false, "quantile_loss": true, "rmsle": true, "rouge": false, "rouge1": false, "rouge2": false, "rougel": false, "sensitivity": false, "silhouette": false, "smape": true, "spearman": false, "specificity": false, "tar": false, "tar_at_far_0_001": false, "top5_accuracy": false, "train_l1": true, "train_l2": true, "val_accuracy": false, "val_auc": false, "val_error_rate": true, "val_f1": false, "val_far": true, "val_fid": true, "val_kid": true, "val_l1": true, "val_l2": true, "val_log_loss": true, "val_mae": true, "val_mape": true, "val_medae": true, "val_meteor": false, "val_mse": true, "val_r2": false, "val_rmse": true, "val_rmsle": true, "val_rouge": false, "val_tar": false, "val_tar_at_far_0_001": false, "wer": true};
export const LOWER_NAME_HINTS: readonly string[] = ["loss", "error", "err", "mae", "mse", "rmse", "perplexity", "ppl", "eer", "nll"];
export const HIGHER_NAME_HINTS: readonly string[] = ["acc", "accuracy", "f1", "auc", "map", "precision", "recall", "iou", "dice", "bleu", "psnr", "ssim", "r2"];

/** Improvement fraction -> grade, best first, for metrics with no scale. */
export const TRAJECTORY_THRESHOLDS: readonly Threshold[] = [["A+", 0.7], ["A", 0.55], ["A-", 0.45], ["B+", 0.35], ["B", 0.25], ["B-", 0.16], ["C+", 0.09], ["C", 0.04], ["C-", 0.005], ["D", -0.03]];

export const FEW_READINGS = 5;

export const AWAKENING_BELOW = 0.1;
/** (phase, advancement bar, improvement bar): see compute_phase. */
export const PHASE_STEPS: readonly [Phase, number, number][] = [["learning", 0.4, 0.4], ["understanding", 0.7, 0.75], ["mastering", 0.95, 0.95]];

export const PAST_PEAK_REL_DROP = 0.01;
export const STALL_MIN_EPOCHS = 3;
export const STALL_REL_IMPROVEMENT = 0.03;
export const OVERFIT_WINDOW = 3;
export const PLATEAU_WINDOW = 5;
export const PLATEAU_DELTA = 0.01;
export const DIVERGE_GROWTH = 10.0;
