"""Generate the extension's engine tables from the Python engine's.

The VS Code extension carries a TypeScript copy of the story engine. Its key
tables were ported by hand and drifted: a differential run over 319 metric
names found 170 that the two engines canonicalised differently — including
`valid_loss` and `eval_loss` becoming TRAINING loss in the extension, and
`val_mae` merging into training MAE. Same log, different task, primary metric
and grade depending on which engine read it.

So the tables are no longer ported; they are generated from the Python source,
and `tests/unit/test_ts_engine_tables_sync.py` fails when the committed file
is stale.

    python scripts/gen_ts_engine_tables.py          # rewrite the TS file
    python scripts/gen_ts_engine_tables.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from epochix.enums import TaskType  # noqa: E402
from epochix.normalizer import canonical_keys as ck  # noqa: E402
from epochix.story_engine import _ON_SCALE_KEYS, _PREFERRED_KEYS_FOR_TASK  # noqa: E402
from epochix.story_engine.task_classifier import _TASK_SIGNALS  # noqa: E402

TARGET = REPO / "epochix-vscode" / "src" / "story" / "engineTables.generated.ts"
# Python's answer for every name below, which the extension's test replays
# through its own canonicaliser: the differential that found the drift, kept.
GOLDEN = REPO / "epochix-vscode" / "src" / "test" / "fixtures" / "canonical.golden.json"

_BASES = (
    "mae", "rmse", "mse", "r2", "mape", "l1", "l2", "loss", "accuracy", "acc", "iou", "miou",
    "dice", "auc", "f1", "precision", "recall", "eer", "perplexity", "map", "map50", "logloss",
    "log_loss", "error", "error_rate", "psnr", "ssim", "fid", "wer", "bleu", "rouge", "medae",
    "rmsle", "mae_cm", "rmse_deg",
)
_PREFIXES = ("", "val_", "valid_", "validation_", "test_", "eval_", "train_", "training_")


def _js(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def _on_scale(task: TaskType) -> list[str]:
    # A CUSTOM run is always graded on how far it moved (needs_trajectory in
    # story_engine/__init__.py), whatever its first preferred key is.
    if task is TaskType.CUSTOM:
        return []
    if task in _ON_SCALE_KEYS:
        return sorted(_ON_SCALE_KEYS[task])
    return list(_PREFERRED_KEYS_FOR_TASK.get(task, ())[:1])


def render() -> str:
    tasks = [t for t in TaskType]
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine",
        "// (normalizer/canonical_keys.py, story_engine/__init__.py,",
        "// story_engine/task_classifier.py). Do not edit: change the Python and",
        "// regenerate. tests/unit/test_ts_engine_tables_sync.py fails if stale.",
        "",
        'import type { TaskType } from "./grader";',
        "",
        "/** Raw (lower-cased) metric name -> canonical name. */",
        "export const CANONICAL_MAP: ReadonlyMap<string, string> = new Map([",
    ]
    lines += [f"  [{_js(k)}, {_js(v)}]," for k, v in ck.CANONICAL_MAP.items()]
    lines += [
        "]);",
        "",
        f"export const SPLIT_PREFIXES: readonly string[] = {_js(list(ck._SPLIT_PREFIXES))};",
        "",
        "export const VALIDATION_PREFIXES: ReadonlySet<string> = new Set("
        f"{_js(sorted(ck._VALIDATION_PREFIXES))});",
        "",
        f"export const UNIT_SUFFIXES: readonly string[] = {_js(list(ck._UNIT_SUFFIXES))};",
        "",
        "/** First match wins; a run matching none is \"custom\". */",
        "export const TASK_SIGNALS: ReadonlyArray<readonly [TaskType, ReadonlySet<string>]> = [",
    ]
    lines += [f"  [{_js(task.value)}, new Set({_js(sorted(keys))})]," for keys, task in _TASK_SIGNALS]
    lines += [
        "];",
        "",
        "/** Primary-metric preference per task, best first. */",
        "export const PREFERRED_KEYS: Readonly<Record<TaskType, readonly string[]>> = {",
    ]
    lines += [
        f"  {t.value}: {_js(list(_PREFERRED_KEYS_FOR_TASK.get(t, ())))}," for t in tasks
    ]
    lines += [
        "};",
        "",
        "/** The metrics a task's absolute grade bands are for; anything else is",
        " *  graded on improvement. */",
        "export const ON_SCALE: Readonly<Record<TaskType, ReadonlySet<string>>> = {",
    ]
    lines += [f"  {t.value}: new Set({_js(_on_scale(t))})," for t in tasks]
    lines += ["};", ""]
    return "\n".join(lines)


def render_golden() -> str:
    names = sorted(set(ck.CANONICAL_MAP) | {p + b for p in _PREFIXES for b in _BASES})
    # Python files unknown names under "custom"; the extension keeps the name.
    golden = {}
    for name in names:
        canonical = ck.canonicalize_key(name)
        golden[name] = name if canonical == "custom" else canonical
    return json.dumps(golden, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    outputs = {TARGET: render(), GOLDEN: render_golden()}
    if "--check" in sys.argv:
        stale = [
            path
            for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text
        ]
        for path in stale:
            print(f"{path.relative_to(REPO)} is stale: run python scripts/gen_ts_engine_tables.py")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
