"""Generate the extension's engine tables from the Python engine's.

The VS Code extension carries a TypeScript copy of the story engine. Its key
tables were ported by hand and drifted: a differential run over 319 metric
names found 170 that the two engines canonicalised differently — including
`valid_loss` and `eval_loss` becoming TRAINING loss in the extension, and
`val_mae` merging into training MAE. Same log, different task, primary metric
and grade depending on which engine read it.

So the tables — and the narrative templates, which were English-only in the
extension — are no longer ported; they are generated from the Python source,
and `tests/unit/test_ts_engine_tables_sync.py` fails when a committed file is
stale.

    python scripts/gen_ts_engine_tables.py          # rewrite the generated files
    python scripts/gen_ts_engine_tables.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from epochix.enums import Phase, TaskType  # noqa: E402
from epochix.normalizer import canonical_keys as ck  # noqa: E402
from epochix.story_engine import _ON_SCALE_KEYS, _PREFERRED_KEYS_FOR_TASK  # noqa: E402
from epochix.story_engine import messages, narrator  # noqa: E402
from epochix.story_engine.task_classifier import _TASK_SIGNALS  # noqa: E402
from epochix.parsers._never_metrics import NEVER_METRICS  # noqa: E402
from epochix.parsers.registry import SNIFF_SAMPLE_LINES, SNIFF_THRESHOLD  # noqa: E402
from epochix.parsers.universal import _NN_REPR_KWARGS  # noqa: E402

TARGET = REPO / "epochix-vscode" / "src" / "story" / "engineTables.generated.ts"
# The narrative templates, per locale, exactly as the Python loader resolves
# them (a missing translation falls back to English there too). The extension
# carried its own English-only copy, so its stories ignored the locale setting.
NARRATIVES = REPO / "epochix-vscode" / "src" / "story" / "narratives.generated.ts"
LOCALES = ("en", "fa", "fr")
# Python's answer for every name below, which the extension's test replays
# through its own canonicaliser: the differential that found the drift, kept.
GOLDEN = REPO / "epochix-vscode" / "src" / "test" / "fixtures" / "canonical.golden.json"

_BASES = (
    "mae", "rmse", "mse", "r2", "mape", "l1", "l2", "loss", "accuracy", "acc", "iou", "miou",
    "dice", "auc", "f1", "precision", "recall", "eer", "perplexity", "map", "map50", "logloss",
    "log_loss", "error", "error_rate", "psnr", "ssim", "fid", "wer", "bleu", "rouge", "medae",
    "rmsle", "mae_cm", "rmse_deg",
)
_PREFIXES = ("", "val_", "valid_", "validation_", "test_", "eval_", "train_", "training_")


def _js(value: object) -> str:
    # Persian needs the zero-width (non-)joiner, but an invisible character in
    # source is what tests/unit/test_source_security.py exists to keep out.
    # Escaped, the string is the same and the source shows what is in it.
    return (
        json.dumps(value, ensure_ascii=False)
        .replace("‌", "\\u200c")
        .replace("‍", "\\u200d")
    )


def _on_scale(task: TaskType) -> list[str]:
    # A CUSTOM run is always graded on how far it moved (needs_trajectory in
    # story_engine/__init__.py), whatever its first preferred key is.
    if task is TaskType.CUSTOM:
        return []
    if task in _ON_SCALE_KEYS:
        return sorted(_ON_SCALE_KEYS[task])
    return list(_PREFERRED_KEYS_FOR_TASK.get(task, ())[:1])


def render() -> str:
    tasks = [t for t in TaskType]
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine",
        "// (normalizer/canonical_keys.py, story_engine/__init__.py,",
        "// story_engine/task_classifier.py). Do not edit: change the Python and",
        "// regenerate. tests/unit/test_ts_engine_tables_sync.py fails if stale.",
        "",
        'import type { TaskType } from "./grader";',
        "",
        "/** Raw (lower-cased) metric name -> canonical name. */",
        "export const CANONICAL_MAP: ReadonlyMap<string, string> = new Map([",
    ]
    lines += [f"  [{_js(k)}, {_js(v)}]," for k, v in ck.CANONICAL_MAP.items()]
    lines += [
        "]);",
        "",
        f"export const SPLIT_PREFIXES: readonly string[] = {_js(list(ck._SPLIT_PREFIXES))};",
        "",
        "export const VALIDATION_PREFIXES: ReadonlySet<string> = new Set("
        f"{_js(sorted(ck._VALIDATION_PREFIXES))});",
        "",
        f"export const UNIT_SUFFIXES: readonly string[] = {_js(list(ck._UNIT_SUFFIXES))};",
        "",
        "/** First match wins; a run matching none is \"custom\". */",
        "export const TASK_SIGNALS: ReadonlyArray<readonly [TaskType, ReadonlySet<string>]> = [",
    ]
    lines += [f"  [{_js(task.value)}, new Set({_js(sorted(keys))})]," for keys, task in _TASK_SIGNALS]
    lines += [
        "];",
        "",
        "/** Primary-metric preference per task, best first. */",
        "export const PREFERRED_KEYS: Readonly<Record<TaskType, readonly string[]>> = {",
    ]
    lines += [
        f"  {t.value}: {_js(list(_PREFERRED_KEYS_FOR_TASK.get(t, ())))}," for t in tasks
    ]
    lines += [
        "};",
        "",
        "/** The metrics a task's absolute grade bands are for; anything else is",
        " *  graded on improvement. */",
        "export const ON_SCALE: Readonly<Record<TaskType, ReadonlySet<string>>> = {",
    ]
    lines += [f"  {t.value}: new Set({_js(_on_scale(t))})," for t in tasks]
    lines += [
        "};",
        "",
        "/** Names that are never a metric: run config, model-summary totals, units",
        " *  (parsers/_never_metrics.py). */",
        f"export const NEVER_METRICS: ReadonlySet<string> = new Set({_js(sorted(NEVER_METRICS))});",
        "",
        "/** Keyword arguments of a torch `print(model)` dump (parsers/universal.py). */",
        f"export const NN_REPR_KWARGS: ReadonlySet<string> = new Set({_js(sorted(_NN_REPR_KWARGS))});",
        "",
        "/** Lines sampled before a parser is chosen (parsers/registry.py). */",
        f"export const SNIFF_SAMPLE_LINES = {SNIFF_SAMPLE_LINES};",
        f"export const SNIFF_THRESHOLD = {SNIFF_THRESHOLD};",
        "",
    ]
    return "\n".join(lines)


def render_narratives() -> str:
    special = {
        "pastPeak": lambda loc: narrator._load_special(
            "_pastpeak", loc, "The run is past its best value."
        ),
        "stalled": narrator._load_stalled,
        "diverged": narrator._load_diverged,
        "singleReading": lambda loc: narrator._load_special(
            "_single_reading", loc, "A single result: {metric} {value}. There is no trend to read."
        ),
    }
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine's",
        "// templates (story_engine/templates) and narrator.py. Do not edit: change",
        "// the Python and regenerate. tests/unit/test_ts_engine_tables_sync.py fails",
        "// if this is stale.",
        "",
        'import type { TaskType } from "./grader";',
        "",
        f"export const LOCALES = {_js(list(LOCALES))} as const;",
        "export type Locale = (typeof LOCALES)[number];",
        "",
        '/** "task/phase" -> variants, per locale. */',
        "export const PHASE_TEMPLATES: Readonly<Record<Locale, Readonly<Record<string, readonly string[]>>>> = {",
    ]
    for loc in LOCALES:
        lines.append(f"  {loc}: {{")
        for task in TaskType:
            for phase in Phase:
                variants = narrator._load_templates(task, phase, loc)
                lines.append(f"    {_js(task.value + '/' + phase.value)}: {_js(variants)},")
        lines.append("  },")
    lines += [
        "};",
        "",
        "/** Phase-independent stories: a run past its peak, stalled, diverged, or a",
        " *  single result with no arc. */",
        "export const SPECIAL_TEMPLATES: Readonly<Record<Locale, Readonly<{",
        "  pastPeak: readonly string[];",
        "  stalled: readonly string[];",
        "  diverged: readonly string[];",
        "  singleReading: readonly string[];",
        "}>>> = {",
    ]
    for loc in LOCALES:
        lines.append(f"  {loc}: {{")
        lines += [f"    {name}: {_js(load(loc))}," for name, load in special.items()]
        lines.append("  },")
    lines += [
        "};",
        "",
        "/** The metrics a task's prose names outright (\"Accuracy {value_pct}\"). For",
        " *  any other primary metric the neutral custom set is used instead. */",
        "export const PROSE_ASSUMES: Readonly<Partial<Record<TaskType, ReadonlySet<string>>>> = {",
    ]
    lines += [
        f"  {task.value}: new Set({_js(sorted(keys))}),"
        for task, keys in narrator._PROSE_ASSUMES.items()
    ]
    lines += [
        "};",
        "",
        "/** How a split prefix is spoken, in the sentence's own language and word order. */",
        "export const METRIC_SPLIT_WORDS: Readonly<Record<Locale, ReadonlyArray<readonly [string, string]>>> = {",
    ]
    lines += [
        f"  {loc}: {_js([list(p) for p in narrator._METRIC_SPLIT_WORDS[loc]])},"
        for loc in LOCALES
    ]
    lines += [
        "};",
        "",
        f"export const NO_METRIC: Readonly<Record<Locale, string>> = {_js(narrator._NO_METRIC)};",
        "",
        "/** Warning and milestone messages (story_engine/messages.py). */",
        "export const MESSAGES: Readonly<Record<Locale, Readonly<Record<string, string>>>> = {",
    ]
    lines += [f"  {loc}: {_js(messages.MESSAGES[loc])}," for loc in LOCALES]
    lines += ["};", ""]
    return "\n".join(lines)


def render_golden() -> str:
    names = sorted(set(ck.CANONICAL_MAP) | {p + b for p in _PREFIXES for b in _BASES})
    # Python files unknown names under "custom"; the extension keeps the name.
    golden = {}
    for name in names:
        canonical = ck.canonicalize_key(name)
        golden[name] = name if canonical == "custom" else canonical
    return json.dumps(golden, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    outputs = {TARGET: render(), NARRATIVES: render_narratives(), GOLDEN: render_golden()}
    if "--check" in sys.argv:
        stale = [
            path
            for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text
        ]
        for path in stale:
            print(f"{path.relative_to(REPO)} is stale: run python scripts/gen_ts_engine_tables.py")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
