"""Generate the extension's engine tables from the Python engine's.

The VS Code extension carries a TypeScript copy of the story engine. Its key
tables were ported by hand and drifted: a differential run over 319 metric
names found 170 that the two engines canonicalised differently — including
`valid_loss` and `eval_loss` becoming TRAINING loss in the extension, and
`val_mae` merging into training MAE. Same log, different task, primary metric
and grade depending on which engine read it.

So the tables — and the narrative templates, which were English-only in the
extension — are no longer ported; they are generated from the Python source,
and `tests/unit/test_ts_engine_tables_sync.py` fails when a committed file is
stale.

    python scripts/gen_ts_engine_tables.py          # rewrite the generated files
    python scripts/gen_ts_engine_tables.py --check  # exit 1 if it is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import epochix.story_engine as engine  # noqa: E402
from epochix.enums import Grade, Phase, TaskType  # noqa: E402
from epochix.normalizer import canonical_keys as ck  # noqa: E402
from epochix.parsers import architecture_parser as arch  # noqa: E402
from epochix.parsers._never_metrics import NEVER_METRICS, VALUE_DECIDES  # noqa: E402
from epochix.parsers.registry import SNIFF_SAMPLE_LINES, SNIFF_THRESHOLD  # noqa: E402
from epochix.parsers import universal as universal_parser  # noqa: E402
from epochix.parsers.universal import _NN_REPR_KWARGS  # noqa: E402
from epochix.story_engine import (  # noqa: E402  # noqa: E402  # noqa: E402
    _ON_SCALE_KEYS,
    _PREFERRED_KEYS_FOR_TASK,
    grade,
    messages,
    narrator,
    phases,
)
from epochix.story_engine import warnings as warnings_mod  # noqa: E402
from epochix.story_engine.task_classifier import _TASK_SIGNALS  # noqa: E402

TARGET = REPO / "epochix-vscode" / "src" / "story" / "engineTables.generated.ts"
# The narrative templates, per locale, exactly as the Python loader resolves
# them (a missing translation falls back to English there too). The extension
# carried its own English-only copy, so its stories ignored the locale setting.
NARRATIVES = REPO / "epochix-vscode" / "src" / "story" / "narratives.generated.ts"
LOCALES = ("en", "fa", "fr")
# Python's answer for every name below, which the extension's test replays
# through its own canonicaliser: the differential that found the drift, kept.
GOLDEN = REPO / "epochix-vscode" / "src" / "test" / "fixtures" / "canonical.golden.json"
# Grading, direction, phase and pathology constants. The logic reading them was
# hand-ported and had drifted (no first-reading phase baseline, an unclamped
# improvement ratio, direction pins Python lacked); now every number is
# generated, and GRADING_GOLDEN pins what the Python functions answer.
GRADING = REPO / "epochix-vscode" / "src" / "story" / "grading.generated.ts"
GRADING_GOLDEN = REPO / "epochix-vscode" / "src" / "test" / "fixtures" / "grading.golden.json"

_BASES = (
    "mae", "rmse", "mse", "r2", "mape", "l1", "l2", "loss", "accuracy", "acc", "iou", "miou",
    "dice", "auc", "f1", "precision", "recall", "eer", "perplexity", "map", "map50", "logloss",
    "log_loss", "error", "error_rate", "psnr", "ssim", "fid", "wer", "bleu", "rouge", "medae",
    "rmsle", "mae_cm", "rmse_deg",
)
_PREFIXES = ("", "val_", "valid_", "validation_", "test_", "eval_", "train_", "training_")


def _js(value: object) -> str:
    # Persian needs the zero-width (non-)joiner, but an invisible character in
    # source is what tests/unit/test_source_security.py exists to keep out.
    # Escaped, the string is the same and the source shows what is in it.
    return (
        json.dumps(value, ensure_ascii=False)
        .replace("‌", "\\u200c")
        .replace("‍", "\\u200d")
    )


def _on_scale(task: TaskType) -> list[str]:
    # A CUSTOM run is always graded on how far it moved (needs_trajectory in
    # story_engine/__init__.py), whatever its first preferred key is.
    if task is TaskType.CUSTOM:
        return []
    if task in _ON_SCALE_KEYS:
        return sorted(_ON_SCALE_KEYS[task])
    return list(_PREFERRED_KEYS_FOR_TASK.get(task, ())[:1])


def render() -> str:
    tasks = [t for t in TaskType]
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine",
        "// (normalizer/canonical_keys.py, story_engine/__init__.py,",
        "// story_engine/task_classifier.py). Do not edit: change the Python and",
        "// regenerate. tests/unit/test_ts_engine_tables_sync.py fails if stale.",
        "",
        'import type { TaskType } from "./grader";',
        "",
        "/** Raw (lower-cased) metric name -> canonical name. */",
        "export const CANONICAL_MAP: ReadonlyMap<string, string> = new Map([",
    ]
    lines += [f"  [{_js(k)}, {_js(v)}]," for k, v in ck.CANONICAL_MAP.items()]
    lines += [
        "]);",
        "",
        f"export const SPLIT_PREFIXES: readonly string[] = {_js(list(ck._SPLIT_PREFIXES))};",
        "",
        "export const VALIDATION_PREFIXES: ReadonlySet<string> = new Set("
        f"{_js(sorted(ck._VALIDATION_PREFIXES))});",
        "",
        f"export const UNIT_SUFFIXES: readonly string[] = {_js(list(ck._UNIT_SUFFIXES))};",
        "",
        "/** First match wins; a run matching none is \"custom\". */",
        "export const TASK_SIGNALS: ReadonlyArray<readonly [TaskType, ReadonlySet<string>]> = [",
    ]
    lines += [f"  [{_js(task.value)}, new Set({_js(sorted(keys))})]," for keys, task in _TASK_SIGNALS]
    lines += [
        "];",
        "",
        "/** Primary-metric preference per task, best first. */",
        "export const PREFERRED_KEYS: Readonly<Record<TaskType, readonly string[]>> = {",
    ]
    lines += [
        f"  {t.value}: {_js(list(_PREFERRED_KEYS_FOR_TASK.get(t, ())))}," for t in tasks
    ]
    lines += [
        "};",
        "",
        "/** The metrics a task's absolute grade bands are for; anything else is",
        " *  graded on improvement. */",
        "export const ON_SCALE: Readonly<Record<TaskType, ReadonlySet<string>>> = {",
    ]
    lines += [f"  {t.value}: new Set({_js(_on_scale(t))})," for t in tasks]
    lines += [
        "};",
        "",
        "/** Names that are never a metric: run config, model-summary totals, units",
        " *  (parsers/_never_metrics.py). */",
        f"export const NEVER_METRICS: ReadonlySet<string> = new Set({_js(sorted(NEVER_METRICS))});",
        "",
        "/** Names that are a setting or a metric depending on the value (is_setting). */",
        f"export const VALUE_DECIDES: ReadonlySet<string> = new Set({_js(sorted(VALUE_DECIDES))});",
        "",
        "/** Keyword arguments of a torch `print(model)` dump (parsers/universal.py). */",
        f"export const NN_REPR_KWARGS: ReadonlySet<string> = new Set({_js(sorted(_NN_REPR_KWARGS))});",
        "",
        "/** Lines sampled before a parser is chosen (parsers/registry.py). */",
        f"export const SNIFF_SAMPLE_LINES = {SNIFF_SAMPLE_LINES};",
        f"export const SNIFF_THRESHOLD = {SNIFF_THRESHOLD};",
        "",
        "/** Layer-type keyword -> [tech label, plain label, visual type], most",
        " *  specific first (parsers/architecture_parser.py). The extension's copy",
        " *  was a hand-kept subset with no ResNet, VGG or YOLO entries. */",
        "export const ARCH_TYPE_MAP: ReadonlyArray<readonly [string, readonly [string, string, string]]> = [",
    ]
    lines += [
        f"  [{_js(k)}, [{_js(m['tech_label'])}, {_js(m['plain_label'])}, {_js(m['visual_type'])}]],"
        for k, m in arch._TYPE_MAP
    ]
    fb = arch._FALLBACK_META
    lines += [
        "];",
        "",
        "export const ARCH_FALLBACK: readonly [string, string, string] = "
        f"[{_js(fb['tech_label'])}, {_js(fb['plain_label'])}, {_js(fb['visual_type'])}];",
        "",
        "/** Layers left out of the diagram when richer ones exist. */",
        f"export const ARCH_TRIVIAL: readonly string[] = {_js(list(arch._TRIVIAL))};",
        "",
        "/** `print(model)` containers opened one level instead of listed. */",
        f"export const ARCH_REPR_CONTAINERS: ReadonlySet<string> = new Set({_js(sorted(arch._REPR_CONTAINERS))});",
        "",
        f"export const ARCH_MAX_LAYERS = {arch._MAX_LAYERS};",
        "",
        "/** A line with this many assignments, this share of them not numbers, is a",
        " *  settings dump and carries no metric (parsers/universal.py). */",
        f"export const CONFIG_DUMP_MIN_PAIRS = {universal_parser.CONFIG_DUMP_MIN_PAIRS};",
        "export const CONFIG_DUMP_NON_NUMERIC_SHARE = "
        f"{universal_parser.CONFIG_DUMP_NON_NUMERIC_SHARE};",
        "",
    ]
    return "\n".join(lines)


# Every corpus log whose architecture Python reads from a `print(model)` dump —
# the format the extension's parser shares with it — and what Python makes of
# it. The extension's test replays each log through its own parser.
ARCH_GOLDEN = REPO / "epochix-vscode" / "src" / "test" / "fixtures" / "architecture.golden.json"


def _arch_rows(layers: list[arch.ArchLayer]) -> list[list[str]]:
    return [
        [lyr.name, lyr.layer_type, lyr.tech_label, lyr.plain_label, lyr.visual_type]
        for lyr in layers
    ]


# `print(model)` shapes the corpus lacks: a model that is itself a Sequential,
# a recurrent model, containers inside containers, a ModuleList.
_ARCH_SAMPLES: dict[str, list[str]] = {
    "sequential_root": [
        "Sequential(",
        "  (0): Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1))",
        "  (1): ReLU()",
        "  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)",
        "  (3): Flatten(start_dim=1, end_dim=-1)",
        "  (4): Linear(in_features=5408, out_features=10, bias=True)",
        ")",
    ],
    "bilstm": [
        "SeqClassifier(",
        "  (embedding): Embedding(10000, 300)",
        "  (lstm): LSTM(300, 256, num_layers=2, bidirectional=True)",
        "  (fc): Linear(in_features=512, out_features=5, bias=True)",
        ")",
    ],
    "nested_containers": [
        "Net(",
        "  (features): Sequential(",
        "    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))",
        "    (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)",
        "    (2): Sequential(",
        "      (0): Conv2d(16, 32, kernel_size=(3, 3), stride=(1, 1))",
        "    )",
        "  )",
        "  (blocks): ModuleList(",
        "    (0-3): 4 x TransformerEncoderLayer(",
        "      (self_attn): MultiheadAttention(",
        "      )",
        "    )",
        "  )",
        "  (head): Linear(in_features=32, out_features=10, bias=True)",
        ")",
    ],
}


def render_arch_golden() -> str:
    logs = sorted(
        [*(REPO / "demo").glob("*.log"), *(REPO / "tests" / "fixtures" / "logs").glob("*.log")]
    )
    from_logs: dict[str, list[list[str]]] = {}
    for path in logs:
        lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        best = arch.parse_architecture(lines)
        repr_only = arch._clean(arch._parse_module_repr(lines))
        if best and _arch_rows(best) == _arch_rows(repr_only):
            from_logs[path.relative_to(REPO).as_posix()] = _arch_rows(best)
    samples = {
        name: {"lines": lines, "layers": _arch_rows(arch.parse_architecture(lines))}
        for name, lines in _ARCH_SAMPLES.items()
    }
    golden = {"logs": from_logs, "samples": samples, "pipeline": _pipeline_architectures(logs)}
    return json.dumps(golden, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


def _pipeline_architectures(logs: list[Path]) -> dict[str, list[list[str]]]:
    """What the whole Python pipeline makes of each corpus log's architecture.

    The extension's engine replays the same logs and must draw the same model:
    it read Keras and `print(model)` only, so a Lightning or Ultralytics run
    had an architecture in the browser and none in VS Code.
    """
    import asyncio

    from epochix.ingester.file_batch import FileBatchIngester
    from epochix.pipeline import run_pipeline
    from epochix.server.hub import Hub
    from epochix.store.sqlite_store import RunStore

    out: dict[str, list[list[str]]] = {}
    for path in logs:
        run = asyncio.run(
            run_pipeline(
                ingester=FileBatchIngester("g", str(path)),
                run_id="g",
                store=RunStore(":memory:"),
                hub=Hub(),
            )
        )
        layers = (run.config or {}).get("architecture") or []
        out[path.relative_to(REPO).as_posix()] = [
            [
                lyr["name"],
                lyr["layer_type"],
                lyr["tech_label"],
                lyr["plain_label"],
                lyr["visual_type"],
            ]
            for lyr in layers
        ]
    return out


def render_narratives() -> str:
    special = {
        "pastPeak": lambda loc: narrator._load_special(
            "_pastpeak", loc, "The run is past its best value."
        ),
        "stalled": narrator._load_stalled,
        "diverged": narrator._load_diverged,
        "singleReading": lambda loc: narrator._load_special(
            "_single_reading", loc, "A single result: {metric} {value}. There is no trend to read."
        ),
    }
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine's",
        "// templates (story_engine/templates) and narrator.py. Do not edit: change",
        "// the Python and regenerate. tests/unit/test_ts_engine_tables_sync.py fails",
        "// if this is stale.",
        "",
        'import type { TaskType } from "./grader";',
        "",
        f"export const LOCALES = {_js(list(LOCALES))} as const;",
        "export type Locale = (typeof LOCALES)[number];",
        "",
        '/** "task/phase" -> variants, per locale. */',
        "export const PHASE_TEMPLATES: Readonly<Record<Locale, Readonly<Record<string, readonly string[]>>>> = {",
    ]
    for loc in LOCALES:
        lines.append(f"  {loc}: {{")
        for task in TaskType:
            for phase in Phase:
                variants = narrator._load_templates(task, phase, loc)
                lines.append(f"    {_js(task.value + '/' + phase.value)}: {_js(variants)},")
        lines.append("  },")
    lines += [
        "};",
        "",
        "/** Phase-independent stories: a run past its peak, stalled, diverged, or a",
        " *  single result with no arc. */",
        "export const SPECIAL_TEMPLATES: Readonly<Record<Locale, Readonly<{",
        "  pastPeak: readonly string[];",
        "  stalled: readonly string[];",
        "  diverged: readonly string[];",
        "  singleReading: readonly string[];",
        "}>>> = {",
    ]
    for loc in LOCALES:
        lines.append(f"  {loc}: {{")
        lines += [f"    {name}: {_js(load(loc))}," for name, load in special.items()]
        lines.append("  },")
    lines += [
        "};",
        "",
        "/** The metrics a task's prose names outright (\"Accuracy {value_pct}\"). For",
        " *  any other primary metric the neutral custom set is used instead. */",
        "export const PROSE_ASSUMES: Readonly<Partial<Record<TaskType, ReadonlySet<string>>>> = {",
    ]
    lines += [
        f"  {task.value}: new Set({_js(sorted(keys))}),"
        for task, keys in narrator._PROSE_ASSUMES.items()
    ]
    lines += [
        "};",
        "",
        "/** How a split prefix is spoken, in the sentence's own language and word order. */",
        "export const METRIC_SPLIT_WORDS: Readonly<Record<Locale, ReadonlyArray<readonly [string, string]>>> = {",
    ]
    lines += [
        f"  {loc}: {_js([list(p) for p in narrator._METRIC_SPLIT_WORDS[loc]])},"
        for loc in LOCALES
    ]
    lines += [
        "};",
        "",
        f"export const NO_METRIC: Readonly<Record<Locale, string>> = {_js(narrator._NO_METRIC)};",
        "",
        "/** Warning and milestone messages (story_engine/messages.py). */",
        "export const MESSAGES: Readonly<Record<Locale, Readonly<Record<string, string>>>> = {",
    ]
    lines += [f"  {loc}: {_js(messages.MESSAGES[loc])}," for loc in LOCALES]
    lines += ["};", ""]
    return "\n".join(lines)


def render_golden() -> str:
    names = sorted(set(ck.CANONICAL_MAP) | {p + b for p in _PREFIXES for b in _BASES})
    # Python files unknown names under "custom"; the extension keeps the name.
    golden = {}
    for name in names:
        canonical = ck.canonicalize_key(name)
        golden[name] = name if canonical == "custom" else canonical
    return json.dumps(golden, indent=1, ensure_ascii=False, sort_keys=True) + "\n"


def _num(value: float) -> str:
    """A number as TypeScript source; JSON has no infinity."""
    if value == float("inf"):
        return "Infinity"
    if value == float("-inf"):
        return "-Infinity"
    return json.dumps(value)


def _bands(rows: list[tuple[Grade, float]]) -> str:
    return "[" + ", ".join(f"[{_js(g.value)}, {_num(v)}]" for g, v in rows) + "]"


def render_grading() -> str:
    """Grading, direction, phase and pathology constants, from the Python engine.

    The logic that reads them is ported once in grader.ts / phases.ts; every
    number it compares against comes from here, and grading.golden.json pins
    what the Python functions answer for a sweep of inputs.
    """
    tasks = list(TaskType)
    classification = grade._DEFAULT_THRESHOLDS[TaskType.CLASSIFICATION]
    lines = [
        "// GENERATED by scripts/gen_ts_engine_tables.py from the Python engine",
        "// (story_engine/grade.py, phases.py, warnings.py, __init__.py).",
        "// Do not edit: change the Python and regenerate.",
        "",
        "export type TaskType = " + " | ".join(_js(t.value) for t in tasks) + ";",
        "export type Grade = " + " | ".join(_js(g.value) for g in Grade) + ";",
        "export type Phase = " + " | ".join(_js(p.value) for p in Phase) + ";",
        "export type Threshold = [Grade, number];",
        "",
        "/** Letter grades best first, without I (incomplete). */",
        "export const GRADE_ORDER: readonly Grade[] = "
        + _js([g.value for g in Grade if g is not Grade.INCOMPLETE])
        + ";",
        "",
        "/** Bands per task, best first; a task without its own uses classification's. */",
        "export const DEFAULT_THRESHOLDS: Readonly<Record<TaskType, readonly Threshold[]>> = {",
    ]
    for task in tasks:
        rows = grade._DEFAULT_THRESHOLDS.get(task, classification)
        lines.append(f"  {task.value}: {_bands(rows)},")
    lines += [
        "};",
        "",
        "export const LOWER_BETTER_TASKS: ReadonlySet<TaskType> = new Set("
        + _js(sorted(t.value for t in grade._LOWER_BETTER))
        + ");",
        "",
        "/** Bands that belong to a metric, not a task: R2 and ROC AUC carry their own scale. */",
        "export const METRIC_THRESHOLDS: Readonly<Record<string, readonly Threshold[]>> = {",
    ]
    for metric, rows in sorted(grade._METRIC_THRESHOLDS.items()):
        lines.append(f"  {_js(metric)}: {_bands(rows)},")
    lines += [
        "};",
        "",
        "export const DIRECTION_BY_KEY: Readonly<Record<string, boolean>> = "
        + _js(dict(sorted(grade._DIRECTION_BY_KEY.items())))
        + ";",
        "export const LOWER_NAME_HINTS: readonly string[] = "
        + _js(list(grade._LOWER_NAME_HINTS))
        + ";",
        "export const HIGHER_NAME_HINTS: readonly string[] = "
        + _js(list(grade._HIGHER_NAME_HINTS))
        + ";",
        "",
        "/** Improvement fraction -> grade, best first, for metrics with no scale. */",
        "export const TRAJECTORY_THRESHOLDS: readonly Threshold[] = "
        + _bands(grade._TRAJECTORY_THRESHOLDS)
        + ";",
        "",
        f"export const FEW_READINGS = {grade.FEW_READINGS};",
        "",
        f"export const AWAKENING_BELOW = {_num(phases.AWAKENING_BELOW)};",
        "/** (phase, advancement bar, improvement bar): see compute_phase. */",
        "export const PHASE_STEPS: readonly [Phase, number, number][] = ["
        + ", ".join(f"[{_js(p.value)}, {_num(a)}, {_num(r)}]" for p, a, r in phases.PHASE_STEPS)
        + "];",
        "",
        f"export const PAST_PEAK_REL_DROP = {_num(engine._PAST_PEAK_REL_DROP)};",
        f"export const STALL_MIN_EPOCHS = {engine._STALL_MIN_EPOCHS};",
        f"export const STALL_REL_IMPROVEMENT = {_num(engine._STALL_REL_IMPROVEMENT)};",
        f"export const OVERFIT_WINDOW = {warnings_mod._OVERFIT_WINDOW};",
        f"export const PLATEAU_WINDOW = {warnings_mod._PLATEAU_WINDOW};",
        f"export const PLATEAU_DELTA = {_num(warnings_mod._PLATEAU_DELTA)};",
        f"export const DIVERGE_GROWTH = {_num(warnings_mod._DIVERGE_GROWTH)};",
        "",
    ]
    return "\n".join(lines)


def _sweep(rows: list[tuple[Grade, float]]) -> list[float]:
    """Every band edge, a hair either side of it, and the far ends."""
    out: set[float] = {0.0, 1.0, -1.0, 1e6, 0.5}
    for _, v in rows:
        if v in (float("inf"), float("-inf")):
            continue
        out.update({v, v - 1e-6, v + 1e-6})
    return sorted(out)


def render_grading_golden() -> str:
    """What the Python functions answer, for the extension's tests to replay."""
    compute = []
    for task in TaskType:
        classification = grade._DEFAULT_THRESHOLDS[TaskType.CLASSIFICATION]
        rows = grade._DEFAULT_THRESHOLDS.get(task, classification)
        for value in _sweep(rows):
            compute.append([task.value, value, None, grade.compute_grade(task, value).value])
        for metric, mrows in grade._METRIC_THRESHOLDS.items():
            for value in _sweep(mrows):
                got = grade.compute_grade(task, value, metric=metric).value
                compute.append([task.value, value, metric, got])

    trajectory = []
    for baseline in (1.0, 0.5, 2.3, 0.0, -1.0, 1e-12):
        for frac in (-0.5, -0.03, -0.02, 0.0, 0.004, 0.005, 0.04, 0.09, 0.16, 0.25, 0.35, 0.45,
                     0.55, 0.7, 0.9):
            for lower in (True, False):
                current = baseline * (1 - frac) if lower else baseline * (1 + frac)
                got = grade.grade_by_trajectory(baseline, current, lower).value
                trajectory.append([baseline, current, lower, got])

    names = sorted(
        set(ck.CANONICAL_MAP)
        | set(ck.CANONICAL_MAP.values())
        | set(grade._DIRECTION_BY_KEY)
        | {p + b for p in _PREFIXES for b in _BASES}
        | {"", "custom", "throughput", "lr", "val_mape_pct", "ppl", "bleu4", "psnr_db"}
    )
    direction = {name: grade.metric_lower_better(name) for name in names}

    relative = []
    phase = []
    values = (0.0, 0.05, 0.3, 0.5, 0.74, 0.76, 0.9, 0.96, 1.0, 1.4)
    for baseline in (0.0, 0.1, 0.5, 1.0, 2.0):
        for value in values:
            for lower in (True, False):
                rel = phases.relative_improvement(value, baseline, lower_better=lower)
                relative.append([value, baseline, lower, rel])
                for progress in (None, 0.0, 0.05, 0.1, 0.39, 0.4, 0.69, 0.7, 0.94, 0.95, 1.0):
                    got = phases.compute_phase(progress, value, baseline, lower_better=lower).value
                    phase.append([progress, value, baseline, lower, got])

    note = []
    for g in (Grade.A, Grade.F, Grade.INCOMPLETE):
        for readings in (0, 1, 2, 4, 5, 6, 200):
            for has_epoch in (True, False):
                for new_best in (True, False):
                    got = grade.grade_note(g, readings, has_epoch=has_epoch, new_best=new_best)
                    note.append([g.value, readings, has_epoch, new_best, got])

    golden = {
        "compute_grade": compute,
        "grade_by_trajectory": trajectory,
        "metric_lower_better": direction,
        "relative_improvement": relative,
        "compute_phase": phase,
        "grade_note": note,
    }
    return json.dumps(golden, indent=0, ensure_ascii=False, sort_keys=True) + "\n"


def main() -> int:
    outputs = {
        TARGET: render(),
        NARRATIVES: render_narratives(),
        GOLDEN: render_golden(),
        GRADING: render_grading(),
        GRADING_GOLDEN: render_grading_golden(),
        ARCH_GOLDEN: render_arch_golden(),
    }
    if "--check" in sys.argv:
        stale = [
            path
            for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8").replace("\r\n", "\n") != text
        ]
        for path in stale:
            print(f"{path.relative_to(REPO)} is stale: run python scripts/gen_ts_engine_tables.py")
        return 1 if stale else 0
    for path, text in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
