#!/usr/bin/env python3
"""Semi-automatic Python → TypeScript parser port helper.

Reads a Python parser file and emits a TypeScript skeleton with:
- Regex constants converted to JS regex literals
- `sniff` and `parse_line` method stubs
- Correct imports from `./base`

Usage::

    python scripts/python-to-ts-parser.py src/model_story/parsers/pytorch_lightning.py
    python scripts/python-to-ts-parser.py src/model_story/parsers/keras_tensorflow.py > out.ts
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


def _py_regex_to_js(py_pattern: str) -> str:
    """Best-effort convert a Python regex string to a JS regex literal."""
    # Remove verbose flags, convert named groups, strip Python-only syntax
    js = py_pattern
    js = re.sub(r"\(\?P<(\w+)>", r"(?<\1>", js)  # named groups
    js = re.sub(r"\\s", r"\\s", js)
    # Wrap in JS regex literal
    js = js.replace("/", r"\/")
    return f"/{js}/"


def _extract_regexes(source: str) -> list[tuple[str, str]]:
    """Extract re.compile(...) assignments as (name, pattern) pairs."""
    results: list[tuple[str, str]] = []
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.Assign):
            if (
                isinstance(node.value, ast.Call)
                and isinstance(node.value.func, ast.Attribute)
                and node.value.func.attr == "compile"
            ):
                for target in node.targets:
                    if isinstance(target, ast.Name):
                        name = target.id
                        args = node.value.args
                        if args and isinstance(args[0], ast.Constant):
                            results.append((name, str(args[0].value)))
    return results


def _extract_class_name(source: str) -> str:
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            return node.name
    return "UnknownParser"


def generate_ts(py_source: str, py_path: Path) -> str:
    regexes = _extract_regexes(py_source)
    class_name = _extract_class_name(py_source)
    # Derive TS class name: strip "Parser" suffix, add back
    ts_name = class_name if class_name.endswith("Parser") else class_name + "Parser"

    lines: list[str] = [
        f"/**",
        f" * TypeScript port of {py_path}",
        f" * AUTO-GENERATED by scripts/python-to-ts-parser.py — review before committing.",
        f" */",
        f'import type {{ Parser, ParserContext, RawMetric }} from "./base";',
        "",
    ]

    for name, pattern in regexes:
        js_re = _py_regex_to_js(pattern)
        lines.append(f"const {name} = {js_re};")
    if regexes:
        lines.append("")

    lines += [
        f"export class {ts_name} implements Parser {{",
        f'  readonly name = "TODO";',
        f"  readonly priority = 50;",
        "",
        f"  sniff(sampleLines: readonly string[]): number {{",
        f"    // TODO: port sniff() from Python",
        f"    void sampleLines;",
        f"    return 0.5;",
        f"  }}",
        "",
        f"  parseLine(line: string, ctx: ParserContext): RawMetric[] {{",
        f"    // TODO: port parse_line() from Python",
        f"    void line; void ctx;",
        f"    return [];",
        f"  }}",
        f"}}",
    ]

    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Semi-auto Python parser → TypeScript skeleton."
    )
    ap.add_argument("file", help="Python parser file to port")
    ap.add_argument("-o", "--output", default=None, help="Output .ts file (default: stdout)")
    args = ap.parse_args()

    py_path = Path(args.file)
    if not py_path.exists():
        print(f"File not found: {py_path}", file=sys.stderr)
        sys.exit(1)

    source = py_path.read_text(encoding="utf-8")
    ts = generate_ts(source, py_path)

    if args.output:
        out = Path(args.output)
        out.write_text(ts, encoding="utf-8")
        print(f"Written to {out}", file=sys.stderr)
    else:
        print(ts)


if __name__ == "__main__":
    main()
