"""Several runs side by side, as a document you can send.

The comparison view overlays the runs' curves and explains the difference in
a paragraph, and none of it could leave the browser: the race GIF animates the
curves, but the explanation and the numbers behind it — each run's grade, its
final and best values, where the best was — existed only on screen. This is
the written version, from the same narrative the view shows.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from epochix.exporters.markdown_export import _code_safe, _md_escape
from epochix.i18n import t
from epochix.story_engine.comparison import narrate_comparison, run_trajectories

if TYPE_CHECKING:
    from epochix.models import Run
    from epochix.store.sqlite_store import RunStore


def build_comparison_markdown(
    run_ids: list[str], store: RunStore, locale: str | None = None
) -> str:
    """A Markdown comparison of *run_ids*, in *locale* or the first run's language.

    Raises ValueError for an unknown id or fewer than two runs.
    """
    if len(run_ids) < 2:
        raise ValueError("A comparison needs at least two runs.")
    runs: list[Run] = []
    for rid in run_ids:
        run = store.get_run(rid)
        if run is None:
            raise ValueError(f"Run not found: {rid!r}")
        runs.append(run)
    if locale is None:
        locale = str(runs[0].config.get("locale", "en")) if runs[0].config else "en"

    frames = [store.get_story_frames(run.id) for run in runs]
    trajectories = run_trajectories(list(zip(runs, frames, strict=True)))

    lines = [f"# {t('cmp.title', locale)}", ""]
    # The same paragraph the comparison view shows, including its refusals:
    # runs on different metrics, or too short to compare, are said to be so.
    lines += [narrate_comparison([tr for tr in trajectories if tr is not None], locale), ""]

    notes = [f[-1].grade_note if f else None for f in frames]
    head = [
        t("cmp.run", locale),
        t("md.grade", locale),
        t("md.primary_metric", locale),
        t("col.final", locale),
        t("cover.best", locale),
        t("md.epochs", locale),
    ]
    if any(notes):
        head.append(t("md.grade_note", locale))
    # Some of these keys are lower-case column labels elsewhere ("final", "best").
    lines.append("| " + " | ".join(h[:1].upper() + h[1:] for h in head) + " |")
    lines.append("|" + "---|" * len(head))
    for run, run_frames, traj, note in zip(runs, frames, trajectories, notes, strict=True):
        label = traj.name if traj is not None else run.name or run.id
        grade = run.final_grade.value if run.final_grade else "—"
        if traj is not None:
            metric = traj.primary_metric
            final = f"{traj.final_value:.4g}"
            best_epoch, best_value = traj.best
            best = f"{best_value:.4g} ({t('cover.epoch_n', locale)} {best_epoch:g})"
            epochs = str(len(traj.values))
        elif run_frames:
            # One reading, or readings without epochs: no trajectory, but the
            # value is real and is shown as what it is.
            metric = run_frames[-1].primary_metric or run.primary_metric
            final = f"{run_frames[-1].primary_metric_value:.4g}"
            best, epochs = "—", str(len(run_frames))
        else:
            metric, final, best, epochs = run.primary_metric, "—", "—", "0"
        cells = [_md_escape(label), f"**{grade}**", f"`{_code_safe(metric)}`", final, best, epochs]
        if any(notes):
            cells.append(t(f"grade_note.{note}", locale) if note else "")
        lines.append("| " + " | ".join(cells) + " |")

    lines += ["", "---", ""]
    ids = ", ".join(f"`{run.id}`" for run in runs)
    lines.append(f"*Generated by [epochix](https://github.com/epochix-dev/epochix) · {ids}*")
    lines.append("")
    return "\n".join(lines)
